/**
 * Serializes CanvasDocument into a portable, self-contained SVG string.
 *
 * Goals:
 *   - valid XML / SVG 1.1 (passes xmllint, opens in browsers and Inkscape);
 *   - renders identically without any JavaScript;
 *   - no external resources, no <script>, no event handler attributes,
 *     no foreignObject, no xlink:href;
 *   - JSON model is embedded verbatim under <metadata id="joplin-canvas-data">,
 *     in CDATA, and is the single source of truth on reload.
 *
 * Layout produced:
 *   <?xml version="1.0" encoding="UTF-8"?>
 *   <svg xmlns="..." version="1.1" width=".." height=".." viewBox="..">
 *     <title>...</title>
 *     <desc>...</desc>
 *     <metadata id="joplin-canvas-data"><![CDATA[...JSON...]]></metadata>
 *     <defs>...arrowhead marker...</defs>
 *     <rect ... background />
 *     ...elements sorted by z...
 *   </svg>
 */

import { CanvasDocument } from './canvasTypes';
import { effectiveViewBounds } from './geometry';
import {
	ARROWHEAD_ID,
	ARROWHEAD_START_ID,
	CANVAS_METADATA_ID,
	MARKER_DIAMOND_FILLED_ID,
	MARKER_DIAMOND_FILLED_START_ID,
	MARKER_DIAMOND_OPEN_ID,
	MARKER_DIAMOND_OPEN_START_ID,
	MARKER_TRIANGLE_ID,
	MARKER_TRIANGLE_START_ID,
	SVG_NAMESPACE,
	SVG_VERSION,
} from './svgConstants';
import { renderElement } from './svgRenderers';
import {
	escapeCdata,
	formatNumber as num,
	safeText,
	stripInvalidXmlChars,
} from './xmlEscape';


/**
 * Serializes a CanvasDocument into a self-contained SVG string.
 * The SVG renders identically without JS. The full JSON model is embedded
 * inside <metadata id="joplin-canvas-data"> wrapped into CDATA.
 */
export function serializeCanvasToSvg(doc: CanvasDocument): string {
	const sortedElements = [...doc.elements].sort((a, b) => a.z - b.z);
	const view = effectiveViewBounds(doc);

	const titleEl = `<title>Canvas Note</title>`;
	const descEl =
		`<desc>Generated by Joplin Canvas Notes. ` +
		`Updated ${safeText(doc.meta.updatedAt)}.</desc>`;

	// Markers for arrowheads. fill="context-stroke" is SVG2 (well supported
	// in Chromium, Firefox, Safari, and Joplin's renderer); for ancient
	// consumers the arrowhead falls back to its default fill which still
	// renders a triangle. The start marker uses orient="auto-start-reverse"
	// so the same geometry renders flipped at the line start.
	//
	// UML markers (triangle / diamond) come in two variants: outline-only
	// (open) which uses fill="#ffffff" so the marker punches a hole through
	// the line, and filled which uses fill="context-stroke" to inherit the
	// line color.
	const arrowMarker = (id: string) =>
		`<marker id="${id}" viewBox="0 0 10 10" refX="9" refY="5"` +
		` markerWidth="8" markerHeight="8" orient="auto-start-reverse">` +
		`<path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker>`;

	const triangleMarker = (id: string) =>
		`<marker id="${id}" viewBox="0 0 12 12" refX="11" refY="6"` +
		` markerWidth="10" markerHeight="10" orient="auto-start-reverse">` +
		`<path d="M 0 0 L 11 6 L 0 12 z"` +
		` fill="#ffffff" stroke="context-stroke" stroke-width="1.2"/></marker>`;

	const diamondMarker = (id: string, filled: boolean) =>
		`<marker id="${id}" viewBox="0 0 16 10" refX="15" refY="5"` +
		` markerWidth="12" markerHeight="10" orient="auto-start-reverse">` +
		`<path d="M 0 5 L 8 0 L 16 5 L 8 10 z"` +
		` fill="${filled ? 'context-stroke' : '#ffffff'}"` +
		` stroke="context-stroke" stroke-width="1.2"/></marker>`;

	const defs =
		`<defs>` +
			arrowMarker(ARROWHEAD_ID) +
			arrowMarker(ARROWHEAD_START_ID) +
			triangleMarker(MARKER_TRIANGLE_ID) +
			triangleMarker(MARKER_TRIANGLE_START_ID) +
			diamondMarker(MARKER_DIAMOND_OPEN_ID, false) +
			diamondMarker(MARKER_DIAMOND_OPEN_START_ID, false) +
			diamondMarker(MARKER_DIAMOND_FILLED_ID, true) +
			diamondMarker(MARKER_DIAMOND_FILLED_START_ID, true) +
		`</defs>`;

	const json = JSON.stringify(doc);
	// XML 1.0 forbids most control chars even inside CDATA, so strip them
	// before embedding. JSON.stringify already escapes them in string values,
	// so this only affects pathological cases.
	const safeJson = stripInvalidXmlChars(json);
	const metadata =
		`<metadata id="${CANVAS_METADATA_ID}"><![CDATA[${escapeCdata(safeJson)}]]></metadata>`;

	const background =
		`<rect x="${num(view.x)}" y="${num(view.y)}" width="${num(view.w)}" height="${num(view.h)}"` +
		` fill="${safeText(doc.background)}"/>`;

	const body = sortedElements
		.map((e) => renderElement(e, { canvasBackground: doc.background }))
		.join('');

	return (
		`<?xml version="1.0" encoding="UTF-8"?>` +
		`<svg xmlns="${SVG_NAMESPACE}" version="${SVG_VERSION}"` +
			` width="${num(view.w)}" height="${num(view.h)}"` +
			` viewBox="${num(view.x)} ${num(view.y)} ${num(view.w)} ${num(view.h)}">` +
			titleEl +
			descEl +
			metadata +
			defs +
			background +
			body +
		`</svg>`
	);
}
