/**
 * Serializes CanvasDocument into a portable, self-contained SVG string.
 *
 * Goals:
 *   - valid XML / SVG 1.1 (passes xmllint, opens in browsers and Inkscape);
 *   - renders identically without any JavaScript;
 *   - no external resources, no <script>, no event handler attributes,
 *     no foreignObject, no xlink:href;
 *   - JSON model is embedded verbatim under <metadata id="joplin-canvas-data">,
 *     in CDATA, and is the single source of truth on reload.
 *
 * Layout produced:
 *   <?xml version="1.0" encoding="UTF-8"?>
 *   <svg xmlns="..." version="1.1" width=".." height=".." viewBox="..">
 *     <title>...</title>
 *     <desc>...</desc>
 *     <metadata id="joplin-canvas-data"><![CDATA[...JSON...]]></metadata>
 *     <defs>...arrowhead marker...</defs>
 *     <rect ... background />
 *     ...elements sorted by z...
 *   </svg>
 */

import { CanvasDocument } from './canvasTypes';
import { effectiveViewBounds } from './geometry';
import {
	ARROWHEAD_ID,
	CANVAS_METADATA_ID,
	SVG_NAMESPACE,
	SVG_VERSION,
} from './svgConstants';
import { renderElement } from './svgRenderers';
import {
	escapeCdata,
	formatNumber as num,
	safeText,
	stripInvalidXmlChars,
} from './xmlEscape';

// Re-exports kept for backwards compatibility with existing imports.
export { CANVAS_METADATA_ID, SVG_NAMESPACE, SVG_VERSION } from './svgConstants';
export { escapeXml, safeText } from './xmlEscape';

/**
 * Serializes a CanvasDocument into a self-contained SVG string.
 * The SVG renders identically without JS. The full JSON model is embedded
 * inside <metadata id="joplin-canvas-data"> wrapped into CDATA.
 */
export function serializeCanvasToSvg(doc: CanvasDocument): string {
	const sortedElements = [...doc.elements].sort((a, b) => a.z - b.z);
	const view = effectiveViewBounds(doc);

	const titleEl = `<title>Canvas Note</title>`;
	const descEl =
		`<desc>Generated by Joplin Canvas Notes. ` +
		`Updated ${safeText(doc.meta.updatedAt)}.</desc>`;

	// Marker for arrowheads. fill="context-stroke" is SVG2 (well supported in
	// Chromium, Firefox, Safari, and Joplin's renderer); for ancient consumers
	// the arrowhead falls back to its default fill which still renders a triangle.
	const defs =
		`<defs>` +
			`<marker id="${ARROWHEAD_ID}" viewBox="0 0 10 10" refX="9" refY="5"` +
				` markerWidth="8" markerHeight="8" orient="auto-start-reverse">` +
				`<path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/>` +
			`</marker>` +
		`</defs>`;

	const json = JSON.stringify(doc);
	// XML 1.0 forbids most control chars even inside CDATA, so strip them
	// before embedding. JSON.stringify already escapes them in string values,
	// so this only affects pathological cases.
	const safeJson = stripInvalidXmlChars(json);
	const metadata =
		`<metadata id="${CANVAS_METADATA_ID}"><![CDATA[${escapeCdata(safeJson)}]]></metadata>`;

	const background =
		`<rect x="${num(view.x)}" y="${num(view.y)}" width="${num(view.w)}" height="${num(view.h)}"` +
		` fill="${safeText(doc.background)}"/>`;

	const body = sortedElements.map(renderElement).join('');

	return (
		`<?xml version="1.0" encoding="UTF-8"?>` +
		`<svg xmlns="${SVG_NAMESPACE}" version="${SVG_VERSION}"` +
			` width="${num(view.w)}" height="${num(view.h)}"` +
			` viewBox="${num(view.x)} ${num(view.y)} ${num(view.w)} ${num(view.h)}">` +
			titleEl +
			descEl +
			metadata +
			defs +
			background +
			body +
		`</svg>`
	);
}
